
services:
  nginx:
    build: .
    container_name: nginx_host
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./conf.d:/etc/nginx/conf.d:rw
      - ./certs:/etc/letsencrypt:rw
      - ./acme-webroot:/var/www/certbot:rw
    restart: unless-stopped

  vhost-ui:
    build: ./vhost-ui
    container_name: nginx_vhost_ui
    ports:
      - "127.0.0.1:81:8080"
    environment:
      NGINX_CONTAINER: nginx_host
    volumes:
      - ./conf.d:/etc/nginx/conf.d:rw
      - ./certs:/etc/letsencrypt:rw
      - ./acme-webroot:/var/www/certbot:rw
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped